name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  review_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install google-generativeai requests jq

      - name: Fetch Pull Request Changes
        run: |
          git fetch origin main
          git diff --unified=0 origin/main -- ':!.github/*' > changes.diff

      - name: Run AI Code Review
        env:
          GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/review_code.py

      - name: Comment on PR
        run: |
          COMMENTS=$(cat ai_review_comments.json) 

          if [ "$COMMENTS" != "[]" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            COMMIT_ID=${{ github.event.pull_request.head.sha }}

            # Get PR diff to find correct positions
            DIFF_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files"
            DIFF=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "$DIFF_URL")

            while IFS= read -r comment; do
              FILE=$(echo "$comment" | jq -r '.file')
              LINE=$(echo "$comment" | jq -r '.line')
              TEXT=$(echo "$comment" | jq -r '.comment')
              CONFIDENCE=$(echo "$comment" | jq -r '.confidence')

              # Append the confidence score to the comment text
              COMMENT_TEXT="${TEXT} (Confidence: ${CONFIDENCE})"

              # Check if the file is in the PR diff
              if ! echo "$DIFF" | jq -e --arg FILE "$FILE" '.[] | select(.filename == $FILE)' > /dev/null; then
                echo "⚠️ Skipping $FILE: Not found in PR diff."
                continue
              fi

              # Post inline review comment using `line` instead of `position`
              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/comments" \
                   -d "{\"body\": \"$TEXT\", \"commit_id\": \"$COMMIT_ID\", \"path\": \"$FILE\", \"line\": $LINE, \"side\": \"RIGHT\"}"
            done <<< "$(echo $COMMENTS | jq -c '.[]')"
          fi
