name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  pull-requests: write-all
  contents: read
  
jobs:
  review_code:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install google-generativeai requests

      - name: Fetch Pull Request Changes
        run: |
          git fetch origin main
          git diff origin/main -- ":!.github/*" > changes.diff

      - name: Run AI Code Review
        env:
          GOOGLE_API_KEY: "AIzaSyCG_xdy6Ye0tuYAG4T3r4V5tK6vTWsZ6ms"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/review_code.py "test_folder/example.py"
